networks:
  laravel_network:
services:
  server:
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - postgres
    container_name: laravel_server
    networks:
      - laravel_network
  php:
    build: 
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./:/var/www/html:delegated
    container_name: laravel_php
    networks:
      - laravel_network
  postgres:
    image: postgres:15-alpine3.21
    restart: unless-stopped
    tty: true
    container_name: laravel_postgres
    env_file: 
      - postgres/.env
    ports:
      - 5433:5432
    networks:
      - laravel_network
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - postgres
    ports:
      - 8090:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - laravel_network
  